[package]
name = "gameoflife-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
three-d = { version = "0.18.2", features = ["egui-gui"] }
three-d-asset = "0.9.2"
winit = "0.28.7"
rfd = "0.15.4"
bitvec = "1"
